### ISSUE TITLE
making iso

### ISSUE THREAD

**Issue by djn3m0** [fust/osdev#2]
Hi,

I managed to build this project but unfortunately I cannot load it in qemu using `qemu-i386 -fda kernel.bin`, can you please tell me how you were testing this os?

have you ever tried to boot this in vmware or virtualbox? 

thanks

**Comment by fust** [comment]
You should compile the OS using a [GCC cross compiler](https://wiki.osdev.org/GCC_Cross-Compiler).
I've added the run_qemu.sh, run_bochs.sh and update_image.sh scripts I'm using in the MM branch, this is the most up-to-date version at the moment.

Edit: I see I have forgotten to answer your last question.
Yes, this is tested on and should succesfully boot on both VMWare and VirtualBox.
